### ISSUE TITLE
Amplify headless Powershell script failing with Cannot create property 'providers' on string error

### ISSUE THREAD

**Issue by cfitzpatrickbardess** [aws-amplify/amplify-cli#10163]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli@latest

### If applicable, what version of Node.js are you using?

16.x

### Amplify CLI Version

8.0.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

The Cognito user pool was imported and not created with the Amplify app

### Amplify Categories

auth, api, hosting

### Amplify Commands

pull

### Describe the bug

When running the Powershell script below, I receive the following error. I have validated the JSON strings, and there does not seem to be an issue with them. 

Error:
```
Amplify version 8.0.0
{"projectName":"synergy","appId":"d1s9d54cg64wus","envName":"cicd","defaultEditor":"vscode"}
{"frontend":"javascript","framework":"vue","config":{"SourceDir":"src","DistributionDir":"dist","BuildCommand":"npm run build","StartCommand":"npm run serve"}}
{"awscloudformation":{"configLevel":"project","useProfile":false,"accessKeyId":"xxx","secretAccessKey":"xxx","region":"us-east-1"}}
{"auth":{"userPoolId":"us-east-1_tSYHbjw61","webClientId":"5f88j081jlsq0g489r7q41e0f0","nativeClientId":"5f88j081jlsq0g489r7q41e0f0"}}
Cannot create property 'providers' on string '{projectName:synergy,appId:d1s9d54cg64wus,envName:cicd,defaultEditor:vscode}'
TypeError: Cannot create property 'providers' on string '{projectName:synergy,appId:d1s9d54cg64wus,envName:cicd,defaultEditor:vscode}'
    at transform (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\input-params-manager.js:45:35)
    at normalizeInputParams (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\input-params-manager.js:12:5)
    at constructInputParams (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\amplify-service-helper.js:32:73)
    at Object.run (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\commands\pull.js:16:75)
    at Object.executeAmplifyCommand (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\index.js:282:29)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async executePluginModuleCommand (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\execution-manager.js:142:5)
    at async executeCommand (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\execution-manager.js:40:9)
    at async Object.run (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\index.js:160:9)
```

Powershell Script:
```
Write-Output "Amplify version $(amplify --version)"

$VUECONFIG = [ordered]@{SourceDir = "src"; DistributionDir = "dist"; BuildCommand = "npm run build"; StartCommand = "npm run serve" }

$AWSCLOUDFORMATIONCONFIG = [ordered]@{ configLevel = "project"; useProfile = $false; accessKeyId = "xxx"; secretAccessKey = "xxx"; region = "us-east-1" }

$AMPLIFY = [ordered]@{ projectName = "amplifyProject"; appId = "d1s9d54cg64wus"; envName = "cicd"; defaultEditor = "vscode" } | ConvertTo-Json -Compress

$FRONTEND = [ordered]@{ frontend = "javascript"; framework = "vue"; config = $VUECONFIG } | ConvertTo-Json -Compress

$PROVIDERS = [ordered]@{ awscloudformation = $AWSCLOUDFORMATIONCONFIG } | ConvertTo-Json -Compress

$AUTHCONFIG = [ordered]@{ userPoolId = "us-east-1_tSYHbjw61"; webClientId = "5f88j081jlsq0g489r7q41e0f0"; nativeClientId = "5f88j081jlsq0g489r7q41e0f0" }

$CATEGORIES = [ordered]@{ auth = $AUTHCONFIG } | ConvertTo-Json -Compress

$CODEGEN = [ordered]@{ generateCode = $false; generateDocs = $false } | ConvertTo-Json -Compress

Write-Output $AMPLIFY
Write-Output $FRONTEND
Write-Output $PROVIDERS
Write-Output $CATEGORIES

if (Test-Path "./amplify") { Remove-Item "./amplify" -Recurse };
if (Test-Path "./src/aws-exports.js") { Remove-Item "./src/aws-exports.js" };


amplify pull --providers $PROVIDERS --amplify $AMPLIFY --frontend $FRONTEND --categories $CATEGORIES --yes | Tee-Object -Variable pull
```

### Expected behavior

Ability to pull the Amplify backend environment with no error

### Reproduction steps

Run the above script in a Windows environment using Powershell

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
2022-04-08T14:52:45.039Z|info : amplify version core  {"version":true,"yes":false}
2022-04-08T14:52:47.236Z|info : amplify pull core  {"amplify":"{projectName:amplifyProject,appId:d1s9d54cg64wus,envName:cicd,defaultEditor:vscode}","providers":"[***]retAccessKey:xxx,region:us-[***]st-[***]}}","frontend":"{frontend:javascript,framework:vue,config:{SourceDir:src,DistributionDir:dist,BuildCommand:npm run build,StartCommand:npm run serve}}","categories":"{auth:{userPoolId:us-east-1_tSYHbjw61,webClientId:5f88j081jlsq0g489r7q41e0f0,nativeClientId:5f88j081jlsq0g489r7q41e0f0}}","yes":true}
2022-04-08T14:52:47.303Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
```

</details>

### Additional information

The reason I am using a Windows environment with Powershell is that using Ubuntu with bash is causing errors with Ubuntu's file path limit when running the amplify publish command. The distribution directory cannot be created.

**Comment by josefaidt** [comment]
Hey @cfitzpatrickbardess :wave: thanks for raising this! Based on this line from the logs you posted, it appears the providers' value is passed as a single string rather than a JSON string:

```
Cannot create property 'providers' on string '{projectName:synergy,appId:d1s9d54cg64wus,envName:cicd,defaultEditor:vscode}'
```

Can you try passing this through `| ConvertTo-Json -Compress` as shown for the other inputs?

**Comment by josefaidt** [comment]
Hey @cfitzpatrickbardess thanks for the clarification! I ran through an example using [zx](https://www.npmjs.com/package/zx) and was able to successfully pull a project. Can you try using the following Node.js script to pull your project?

```js
// pull.mjs
import { $ } from 'zx'

const AMPLIFY_APP_ID = 'd3mevdutihu9jw'

const FRONTEND = {
  frontend: 'javascript',
  framework: 'vue',
  config: {
    SourceDir: 'src',
    DistributionDir: 'dist',
    BuildCommand: 'npm run build',
    StartCommand: 'npm run serve',
  },
}

const AMPLIFY = {
  projectName: '10070',
  appId: AMPLIFY_APP_ID,
  envName: 'dev',
  defaultEditor: 'vscode',
}

const PROVIDERS = {
  awscloudformation: {
    configLevel: 'project',
    useProfile: true,
    profileName: 'default',
    // accessKeyId: 'xxx',
    // secretAccessKey: 'xxx',
    region: 'us-east-1',
  },
}

await $`amplify pull \
  --providers ${JSON.stringify(PROVIDERS)} \
  --amplify ${JSON.stringify(AMPLIFY)} \
  --frontend ${JSON.stringify(FRONTEND)} \
  --yes`
```

**Comment by cfitzpatrickbardess** [comment]
Hi @josefaidt, initially I was getting this error (note the '$' preceding the pull command). 

```
$ amplify pull   --providers $'{"awscloudformation":{"configLevel":"project","useProfile":true,"profileName":"default","region":"us-east-1"}}'   --amplify $'{"projectName":"synergy","appId":"d1s9d54cg64wus","envName":"cicd","defaultEditor":"vscode"}'   --frontend $'{"frontend":"javascript","framework":"vue","config":{"SourceDir":"src","DistributionDir":"dist","BuildCommand":"npm run build","StartCommand":"npm run serve"}}'   --yes
🛑 Cannot create property 'providers' on string '$'{projectName:synergy,appId:d1s9d54cg64wus,envName:cicd,defaultEditor:vscode}''
TypeError: Cannot create property 'providers' on string '$'{projectName:synergy,appId:d1s9d54cg64wus,envName:cicd,defaultEditor:vscode}''
    at transform (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\input-params-manager.js:45:35)
    at normalizeInputParams (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\input-params-manager.js:12:5)
    at constructInputParams (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\amplify-service-helper.js:32:73)
    at Object.run (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\commands\pull.js:16:75)
    at Object.executeAmplifyCommand (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\index.js:282:29)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async executePluginModuleCommand (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\execution-manager.js:142:5)
    at async executeCommand (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\execution-manager.js:40:9)
    at async Object.run (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\index.js:160:9)
file:///C:/Users/cfitzpatrick/Documents/GitHub/Synergy-UI/.github/scripts/node_modules/zx/src/index.mjs:99
      let output = new ProcessOutput({
                   ^

ProcessOutput [Error]:
    at file:///C:/Users/cfitzpatrick/Documents/GitHub/Synergy-UI/.github/scripts/amplify-publish.mjs:34:8
    exit code: 1
    at ChildProcess.<anonymous> (file:///C:/Users/cfitzpatrick/Documents/GitHub/Synergy-UI/.github/scripts/node_modules/zx/src/index.mjs:99:20)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

I found this issue describing what I was experiencing: [https://github.com/google/zx/issues/164#issuecomment-886630046](https://github.com/google/zx/issues/164#issuecomment-886630046)

So I updated the code to:
```
const command = `amplify pull \
  --providers ${JSON.stringify(PROVIDERS)} \
  --amplify ${JSON.stringify(AMPLIFY)} \
  --frontend ${JSON.stringify(FRONTEND)} \
  --yes`

await $([command])
```

And I am still receiving an error:

```
$ amplify pull   --providers {"awscloudformation":{"configLevel":"project","useProfile":true,"profileName":"default","region":"us-east-1"}}   --amplify {"projectName":"synergy","appId":"d1s9d54cg64wus","envName":"cicd","defaultEditor":"vscode"}   --frontend {"frontend":"javascript","framework":"vue","config":{"SourceDir":"src","DistributionDir":"dist","BuildCommand":"npm run build","StartCommand":"npm run serve"}}   --yes
🛑 Cannot create property 'providers' on string '{projectName:synergy,appId:d1s9d54cg64wus,envName:cicd,defaultEditor:vscode}'
TypeError: Cannot create property 'providers' on string '{projectName:synergy,appId:d1s9d54cg64wus,envName:cicd,defaultEditor:vscode}'
    at transform (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\input-params-manager.js:45:35)
    at normalizeInputParams (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\input-params-manager.js:12:5)
    at constructInputParams (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\amplify-service-helper.js:32:73)
    at Object.run (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\commands\pull.js:16:75)
    at Object.executeAmplifyCommand (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\index.js:282:29)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async executePluginModuleCommand (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\execution-manager.js:142:5)
    at async executeCommand (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\execution-manager.js:40:9)
    at async Object.run (C:\snapshot\node_modules\@aws-amplify\cli-internal\lib\index.js:160:9)
file:///C:/Users/cfitzpatrick/Documents/GitHub/Synergy-UI/.github/scripts/node_modules/zx/src/index.mjs:99
      let output = new ProcessOutput({
                   ^

ProcessOutput [Error]:
    at file:///C:/Users/cfitzpatrick/Documents/GitHub/Synergy-UI/.github/scripts/amplify-publish.mjs:40:7
    exit code: 1
    at ChildProcess.<anonymous> (file:///C:/Users/cfitzpatrick/Documents/GitHub/Synergy-UI/.github/scripts/node_modules/zx/src/index.mjs:99:20)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

I am also attaching the logs in case they're helpful
[amplify-cli-2022-04-12.log](https://github.com/aws-amplify/amplify-cli/files/8473379/amplify-cli-2022-04-12.log)

**Comment by josefaidt** [comment]
Hey @cfitzpatrickbardess thank you for clarifying and trying out that script. I did notice the providers string still does not appear to be a valid JSON string, however I will try to reproduce this in Windows and see what sort of results I get with the provided PowerShell script

**Comment by josefaidt** [comment]
Hey @cfitzpatrickbardess :wave: I've taken another pass on this with @ykethan and it appears the values we're passing to each of the flags on headless `amplify pull` are not getting parsed from JSON string to an Object, which is causing the error "cannot create property 'providers' on '{...}'". Without diving into the specifics of string escapes in PowerShell we have a couple options:

1. ask the [Discord Community](https://discord.gg/invite/amplify) for scripting assistance
2. install [WSL](https://docs.microsoft.com/en-us/windows/wsl/install) and use the sample bash script from the docs
3. install [WSL](https://docs.microsoft.com/en-us/windows/wsl/install) and use the Node script posted above

I apologize for not being of immediate assistance, however this is outside the scope of support I can provide at this time.

**Comment by josefaidt** [comment]
Closing due to inactivity
