### ISSUE TITLE
amplify function update -> Cannot destructure property 'serviceWalkthroughFilename' of 'serviceMetadata'

### ISSUE THREAD

**Issue by conorw** [aws-amplify/amplify-cli#11260]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14

### Amplify CLI Version

10.3.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

none

### Amplify Categories

auth, analytics, notifications

### Amplify Commands

update

### Describe the bug

Since 10.3.1, when performing an amplify update, changing resource permissions will result in the following error:
Rolling back to 10.0.0 fixes the issue 

⚠️ Could not get policies for analytics: projectname
Policies cannot be added for analytics
TypeError: Cannot destructure property 'serviceWalkthroughFilename' of 'serviceMetadata' as it is undefined.
at Object.getPermissionPolicies (C:\snapshot\repo\build\node_modules\amplify-category-analytics\lib\provider-utils\awscloudformation\index.js:56:5)
    at C:\snapshot\repo\build\node_modules\amplify-category-analytics\lib\index.js:112:32
    at Array.forEach (<anonymous>)
    at getPermissionPolicies (C:\snapshot\repo\build\node_modules\amplify-category-analytics\lib\index.js:102:35)
    at AmplifyToolkit.invokePluginMethod [as _invokePluginMethod] (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\extensions\amplify-helpers\invoke-plugin-method.js:39:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getResourcesForCfn (C:\snapshot\repo\build\node_modules\amplify-category-function\lib\provider-utils\awscloudformation\service-walkthroughs\execPermissionsWalkthrough.js:183:56)
    at async askExecRolePermissionsQuestions (C:\snapshot\repo\build\node_modules\amplify-category-function\lib\provider-utils\awscloudformation\service-walkthroughs\execPermissionsWalkthrough.js:113:66)
    at async Object.updateWalkthrough (C:\snapshot\repo\build\node_modules\amplify-category-function\lib\provider-utils\awscloudformation\service-walkthroughs\lambda-walkthrough.js:197:38)
    at async updateFunctionResource (C:\snapshot\repo\build\node_modules\amplify-category-function\lib\provider-utils\awscloudformation\index.js:155:22)
    at async Object.executeAmplifyCommand (C:\snapshot\repo\build\node_modules\amplify-category-function\lib\index.js:267:5)       
    at async executePluginModuleCommand (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\execution-manager.js:142:5)
    at async executeCommand (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\execution-manager.js:40:9)
    at async Object.run (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\index.js:153:5)

### Expected behavior

Able to update the resource permissions for a function

### Reproduction steps

1. add api, auth, analytics and notifications to project
2. Add a lambda function
3. Update resource permissions using amplify function update, to add permissions to the 'analytics' resource

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

3bd747f16af991e4d8595be2c88f28e0

### Log output

<details>

```
# Put your logs below this line

⚠️ Could not get policies for analytics: projectname
Policies cannot be added for analytics
TypeError: Cannot destructure property 'serviceWalkthroughFilename' of 'serviceMetadata' as it is undefined.
at Object.getPermissionPolicies (C:\snapshot\repo\build\node_modules\amplify-category-analytics\lib\provider-utils\awscloudformation\index.js:56:5)
    at C:\snapshot\repo\build\node_modules\amplify-category-analytics\lib\index.js:112:32
    at Array.forEach (<anonymous>)
    at getPermissionPolicies (C:\snapshot\repo\build\node_modules\amplify-category-analytics\lib\index.js:102:35)
    at AmplifyToolkit.invokePluginMethod [as _invokePluginMethod] (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\extensions\amplify-helpers\invoke-plugin-method.js:39:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getResourcesForCfn (C:\snapshot\repo\build\node_modules\amplify-category-function\lib\provider-utils\awscloudformation\service-walkthroughs\execPermissionsWalkthrough.js:183:56)
    at async askExecRolePermissionsQuestions (C:\snapshot\repo\build\node_modules\amplify-category-function\lib\provider-utils\awscloudformation\service-walkthroughs\execPermissionsWalkthrough.js:113:66)
    at async Object.updateWalkthrough (C:\snapshot\repo\build\node_modules\amplify-category-function\lib\provider-utils\awscloudformation\service-walkthroughs\lambda-walkthrough.js:197:38)
    at async updateFunctionResource (C:\snapshot\repo\build\node_modules\amplify-category-function\lib\provider-utils\awscloudformation\index.js:155:22)
    at async Object.executeAmplifyCommand (C:\snapshot\repo\build\node_modules\amplify-category-function\lib\index.js:267:5)       
    at async executePluginModuleCommand (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\execution-manager.js:142:5)
    at async executeCommand (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\execution-manager.js:40:9)
    at async Object.run (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\index.js:153:5)

```

</details>

### Additional information

rolling back to 10.0.0 fixes the issue

**Comment by ykethan** [comment]
Hey @conorw, thank you for reaching out. I was able to reproduce the issue with the following steps. 
CLI version 10.3.2

1. amplify init
2. amplify add analytics
3. amplify add function 
```
amplify add function
? Select which capability you want to add: Lambda function (serverless function)
? Provide an AWS Lambda function name: auth11247eabe9177
? Choose the runtime that you want to use: NodeJS
? Choose the function template that you want to use: Hello World
? Do you want to configure advanced settings? Yes
? Do you want to access other resources in this project from your Lambda function? Yes
? Select the categories you want this function to have access to. analytics
? Select the operations you want to permit on auth11247 create, read
```

observed the following error.

```
Could not get policies for analytics: auth11247
Policies cannot be added for analytics
TypeError: Cannot destructure property 'serviceWalkthroughFilename' of 'serviceMetadata' as it is undefined.
    at Object.getPermissionPolicies (C:\snapshot\repo\build\node_modules\amplify-category-analytics\lib\provider-utils\awscloudformation\index.js:56:5)
    at C:\snapshot\repo\build\node_modules\amplify-category-analytics\lib\index.js:112:32
    at Array.forEach (<anonymous>)
    at getPermissionPolicies (C:\snapshot\repo\build\node_modules\amplify-category-analytics\lib\index.js:102:35)
    at AmplifyToolkit.invokePluginMethod [as _invokePluginMethod] (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\extensions\amplify-helpers\invoke-plugin-method.js:39:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getResourcesForCfn (C:\snapshot\repo\build\node_modules\amplify-category-function\lib\provider-utils\awscloudformation\service-walkthroughs\execPermissionsWalkthrough.js:183:56)
    at async askExecRolePermissionsQuestions (C:\snapshot\repo\build\node_modules\amplify-category-function\lib\provider-utils\awscloudformation\service-walkthroughs\execPermissionsWalkthrough.js:113:66)
    at async Object.createWalkthrough (C:\snapshot\repo\build\node_modules\amplify-category-function\lib\provider-utils\awscloudformation\service-walkthroughs\lambda-walkthrough.js:53:83)
    at async addFunctionResource (C:\snapshot\repo\build\node_modules\amplify-category-function\lib\provider-utils\awscloudformation\index.js:78:9)
    at async Object.executeAmplifyCommand (C:\snapshot\repo\build\node_modules\amplify-category-function\lib\index.js:267:5)
    at async executePluginModuleCommand (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\execution-manager.js:142:5)
    at async executeCommand (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\execution-manager.js:40:9)
    at async Object.run (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\index.js:153:5)

```

Note: ran `amplify push` to check if the Lambda role updates with the policy but did not observe any additional permissions.
running update function with resource access permissions shows analytics as not selected. 

Marking this as a bug. Thank you for reporting.

**Comment by mjmostachetti** [comment]
Does this also include the bug associated with adding notification resources to a function?

Policies cannot be added for notifications
PluginMethodNotFoundError: Method getPermissionPolicies does not exist or is not a function in category plugin: notifications.
    at amplifyErrorWithTroubleshootingLink (/snapshot/repo/build/node_modules/amplify-cli-core/lib/errors/amplify-error.js:12:85)
    at AmplifyToolkit.invokePluginMethod [as _invokePluginMethod] (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/invoke-plugin-method.js:35:74)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getResourcesForCfn (/snapshot/repo/build/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.js:183:56)
    at async askExecRolePermissionsQuestions (/snapshot/repo/build/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.js:113:66)
    at async Object.createWalkthrough (/snapshot/repo/build/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.js:53:83)
    at async addFunctionResource (/snapshot/repo/build/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/index.js:78:9)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/amplify-category-function/lib/index.js:267:5)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:142:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:40:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:153:5)

**Comment by ykethan** [comment]
Hey @mjmostachetti , thank you for reporting. I was able to reproduce the issue and created a new issue https://github.com/aws-amplify/amplify-cli/issues/11320 to better track this.

**Comment by lazpavel** [comment]
closing as fixed in v10.4.0

**Comment by sujit13666** [comment]
@lazpavel No it didn't got fixed
![Screen Shot 2022-11-09 at 7 06 25 pm](https://user-images.githubusercontent.com/5456641/200773717-0b3c259c-7920-4240-9c58-0248e0daebc1.png)

**Comment by lazpavel** [comment]
@sujit13666 thank you, still pending release, this was merged after the 10.4.0 was created

**Comment by sujit13666** [comment]
@lazpavel Please can you confirm when it will be released? I can't seem to add analytics in the lambda function in anyway. The existing generated cloudformation templates are also rejecting which has analytics in them with errors that template is malformed. But the same template is working in Dev and QA envronment.

**Comment by caesarisme** [comment]
@lazpavel still having the issue on 10.5.2

<img width="1477" alt="image" src="https://user-images.githubusercontent.com/47120775/209465225-8502a9d0-3b71-4970-bf78-5952d2039a62.png">

**Comment by ykethan** [comment]
Reopening the issue.
Thank you for reporting this, I was able to reproduce this issue. observed the following error when providing Lambda function access to user pool groups.

```
? Select the categories you want this function to have access to. auth
? Auth has 2 resources in this project. Select the one you would like your Lambda to access test9b389920, userPoolGroups
? Select the operations you want to permit on test9b389920 create, read, update, delete
? Select the operations you want to permit on userPoolGroups create, read, update, delete
Could not get policies for auth: userPoolGroups
Policies cannot be added for auth
TypeError: Cannot destructure property 'serviceWalkthroughFilename' of 'getSupportedServices(...)[service]' as it is undefined.
    at Object.getPermissionPolicies (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/index.js:359:13)
    at /snapshot/repo/build/node_modules/@aws-amplify/amplify-category-auth/lib/index.js:319:67
    at Array.forEach (<anonymous>)
    at getPermissionPolicies (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-auth/lib/index.js:314:37)
    at AmplifyToolkit.invokePluginMethod [as _invokePluginMethod] (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/extensions/amplify-helpers/invoke-plugin-method.js:39:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getResourcesForCfn (/snapshot/repo/build/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.js:183:56)
    at async askExecRolePermissionsQuestions (/snapshot/repo/build/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.js:113:66)
    at async Object.createWalkthrough (/snapshot/repo/build/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.js:53:83)
    at async addFunctionResource (/snapshot/repo/build/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/index.js:78:9)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/amplify-category-function/lib/index.js:267:5)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:142:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:40:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:153:5)

```

Note: tested when on testing in `11.0.0-beta.3`

```
Could not get policies for auth: userPoolGroups
PluginPolicyAddError: Policies cannot be added for auth
    at askExecRolePermissionsQuestions (/snapshot/repo/build/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.js:129:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.createWalkthrough (/snapshot/repo/build/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.js:53:83)
    at async addFunctionResource (/snapshot/repo/build/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/index.js:78:9)
    at async Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/amplify-category-function/lib/index.js:268:5)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:142:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:40:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:119:5)
There was an error adding the function resource
```

**Comment by ykethan** [comment]
Hey @caesarisme, I have created a new issue providing the above information and replication steps here: https://github.com/aws-amplify/amplify-cli/issues/11664. please do subscribe to the issue for any updates.
