### ISSUE TITLE
Pushing New Environment - Resources Missing from the cli

### ISSUE THREAD

**Issue by mjmostachetti** [aws-amplify/amplify-cli#11891]
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

10.7.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

NO

### Describe the bug

Run `amplify env add`
Run `amplify push`
Run `amplify pull`

### Expected behavior

I should see the state of my resources in the CLI. There is nothing there.

amplify pull

Pre-pull status:

    Current Environment: isitfixed

┌───────────────┬────────────────────────────────┬───────────┬───────────────────┐
│ Category      │ Resource name                  │ Operation │ Provider plugin   │
├───────────────┼────────────────────────────────┼───────────┼───────────────────┤
│ Notifications │ asdf                     │ Create    │                   │
├───────────────┼────────────────────────────────┼───────────┼───────────────────┤
│ Analytics     │ asdf                     │ No Change │ awscloudformation │
├───────────────┼────────────────────────────────┼───────────┼───────────────────┤
│ Api           │ asdf                          │ No Change │ awscloudformation │
├───────────────┼────────────────────────────────┼───────────┼───────────────────┤
│ Api           │ asdf                         │ No Change │ awscloudformation │
├───────────────┼────────────────────────────────┼───────────┼───────────────────┤
│ Auth          │ asdf                 │ No Change │ awscloudformation │
├───────────────┼────────────────────────────────┼───────────┼───────────────────┤
│ Auth          │ asdf                 │ No Change │ awscloudformation │
├───────────────┼────────────────────────────────┼───────────┼───────────────────┤
│ Function      │ asdf                     │ No Change │ awscloudformation │
├───────────────┼────────────────────────────────┼───────────┼───────────────────┤
│ Function      │ asdf │ No Change │ awscloudformation │
├───────────────┼────────────────────────────────┼───────────┼───────────────────┤
│ Function      │ asdf             │ No Change │ awscloudformation │
└───────────────┴────────────────────────────────┴───────────┴───────────────────┘

⚠️ Local changes detected.
⚠️ Pulling changes from the cloud will override your local changes.
? Are you sure you would like to continue? Yes
✔ Successfully pulled backend environment isitfixed from the cloud.
✅
Post-pull status:

    Current Environment: isitfixed

┌──────────┬───────────────┬───────────┬─────────────────┐
│ Category │ Resource name │ Operation │ Provider plugin │
└──────────┴───────────────┴───────────┴─────────────────┘

### Reproduction steps

See above.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by Amplifiyer** [comment]
I believe it's the same issue as fixed in this PR https://github.com/aws-amplify/amplify-cli/pull/11494 , which will be part of our next release.

Can you confirm if you saw the below error when you did `amplify push`
`🛑 Cannot set property 'Id' of undefined`

**Comment by mjmostachetti** [comment]
Yes. I did see that.

**Comment by josefaidt** [comment]
Hey @mjmostachetti :wave: as @Amplifiyer this is a duplicate of a few active bugs, which is resolved with the release of Amplify CLI 10.7.0

- https://github.com/aws-amplify/amplify-cli/issues/11768
- https://github.com/aws-amplify/amplify-cli/issues/11819
- https://github.com/aws-amplify/amplify-cli/issues/11432
- https://github.com/aws-amplify/amplify-cli/issues/11844

**Comment by mjmostachetti** [comment]
Im confused. I’m on 10.7.0 and it is not resolved on that version.

**Comment by Amplifiyer** [comment]
It'll be part of the next release. I'll share once a RC is out so you can test with it.

**Comment by josefaidt** [comment]
Yes, my apologies this fix will be available in 10.8.x

**Comment by edwardfoyle** [comment]
This is resolved in version 10.8.0 of the CLI. Please upgrade to try it out.

**Comment by danielvouch** [comment]
This does not seem to be resolved in 12.5.0 we are getting the same issue
