### ISSUE TITLE
During "amplify add api" command line processing, process exists prematurely

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-cli#1649]
Bug:

During "amplify add api" command line processing, process exists prematurely

To Reproduce

> amplify add api
select "GraphQL"
enter API name
choose authentication type: Amazon Cognito User Pool

The list of options is then displayed but the processing drops to a command line prompt.

**Expected behavior**
Continue processing to create Amplify API

**Screenshots**
Please see screenshot showing the issue.

OS
Microsoft Windows [Version 10.0.17763.475]

![amplify-drop-to-command](https://user-images.githubusercontent.com/29442183/59324277-26849f00-8cac-11e9-9780-2195285cf1aa.png)

**Comment by kaustavghosh06** [comment]
Which node version do you have on your system currently?

**Comment by blairtaylor** [comment]
node version is v10.10.0

**Comment by yuth** [comment]
@blairtaylor could you try using CLI with [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)

Whats the version of Amplify CLI do you have installed? You can get the version by running `amplify -v`

**Comment by blairtaylor** [comment]
Amplify version is 1.7.2. I will try via WSL.

**Comment by blairtaylor** [comment]
- installed WSL
- installed Ubuntu
- installed node (8.10.1) & npm (3.5.2)
> npm install -g @aws-amplify/cli (seems to install correctly)
> amplify configure

- throws the following error (seems to be spawning cmd to launch the AWS site):

Follow these steps to set up access to your AWS account:

Sign in to your AWS administrator account:
https://console.aws.amazon.com/
Press Enter to continue
2019-06-12T23:15:56.142Z - error: uncaughtException: spawn cmd.exe ENOENT date=Wed Jun 12 2019 19:15:56 GMT-0400 (DST), pid=15337, uid=0, gid=0, cwd=/mnt/c/code/aws/amplify/test/test-react-app, execPath=/usr/bin/node, version=v8.10.0, argv=[/usr/bin/node, /usr/local/bin/amplify, configure], rss=261820416, heapTotal=226242560, heapUsed=180160584, external=10466458, loadavg=[0.5185546875, 0.57763671875, 0.5859375], uptime=3382, trace=[column=11, file=util.js, function=_errnoException, line=1022, method=null, native=false, column=19, file=internal/child_process.js, function=Process.ChildProcess._handle.onexit, line=190, method=onexit, native=false, column=16, file=internal/child_process.js, function=onErrorNT, line=372, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickDomainCallback, line=218, method=_tickDomainCallback, native=false, column=11, file=module.js, function=Module.runMain, line=695, method=runMain, native=false, column=16, file=bootstrap_node.js, function=startup, line=188, method=null, native=false, column=3, file=bootstrap_node.js, function=null, line=609, method=null, native=false], stack=[Error: spawn cmd.exe ENOENT,     at _errnoException (util.js:1022:11),     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19),     at onErrorNT (internal/child_process.js:372:16),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickDomainCallback (internal/process/next_tick.js:218:9),     at Function.Module.runMain (module.js:695:11),     at startup (bootstrap_node.js:188:16),     at bootstrap_node.js:609:3]

**Comment by yuth** [comment]
This might be similar to https://github.com/aws-amplify/amplify-cli/issues/1647

**Comment by blairtaylor** [comment]
Additional diagnostic info. This issue only occurs when authorization type for the API is "Amazon Cognito User Pool". If I choose "API key" as authorization type, processing continues normally. I am running the command prompt as administrator.

**Comment by yuth** [comment]
@blairtaylor do you see any additional error when CLI stops? Especially when adding "API" with "Amazon Cognito UserPool"

**Comment by blairtaylor** [comment]
No. As per the initial screenshot, it simply drops to the command line.

**Comment by UnleashedMind** [comment]
@blairtaylor 
The second error you saw when you try it on WSL is probably already fixed by #1655 
I also tried to reproduce the directly on a Windows 10 machine, with 
node v10.16.0
amplify v 1.7.4
But I was not able to reproduce the error on both cmd.exe and Powershell.

**Comment by blairtaylor** [comment]
Aside from this issue, I had been using Windows (not WSL) quite successfully. I don't really think "use WSL instead of native Windows" is a resolution to the issue. I believe this is a bug.

**Comment by kaustavghosh06** [comment]
@blairtaylor Did you try out the new version of the CLI? We're handling this case gracefully and the process shouldn't exit prematurely if the browser isn't able to open up on WSL.

**Comment by oliyoung** [comment]
I'm getting this error still

`$ amplify api update
? Please select from one of the below mentioned services GraphQL
? Choose an authorization type for the API Amazon Cognito User Pool
Using service: Cognito, provided by: awscloudformation

 The current configured provider is Amazon Cognito. 

 Do you want to use the default authentication and security configuration? Default configuration with Social Provider (Federation)
 Warning: you will not be able to edit these selections.
 How do you want users to be able to sign in? (Use arrow keys)
> Username
  Email
  Phone Number
  Email and Phone Number
  I want to learn more. `

`$ amplify -v
1.8.1`

Reproducible with WSL, cmd.exe, gitcmd.exe **and** Powershell

**Comment by oliyoung** [comment]
Fixed by upgrading node to 12.6.0

**Comment by blairtaylor** [comment]
This was also fixed for me by upgrading node to 12.6.0.
