### ISSUE TITLE
Amplify GraphQL Request "Missing authorization header"

### ISSUE THREAD

**Issue by mwarger** [aws-amplify/amplify-cli#1770]
**Describe the bug**
While using the API.graphql call - I'm receiving a GraphQL error that says "Request failed with status code 401".  The underlying network request fails:

errorType: "UnauthorizedException"
message: "Missing authorization header"

**To Reproduce**
1. Setup a multi-environment project with a single environment using Amplify-CLI
2. Deploy everything
3. Run a graphQL query

**Expected behavior**
The request should work.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

I don't get much back in the way of logs or any other errors, so I know this is a little sparse.  I'm happy to answer any questions.

**Comment by kaustavghosh06** [comment]
@ajhool Does your `backend-config.json` file doesn't have a securityType in it? That might be one of the reasons. I just gave it a try and it was populating the securityType for me. Are you still having this issue?

**Comment by ajhool** [comment]
@kaustavghosh06 

```
	"api": {
		"myapi": {
			"service": "AppSync",
			"providerPlugin": "awscloudformation"
		}
	},
```

My backend-config.js does not have securityType. I am still having this issue. Should I add securityType to `myApi`?

**Comment by kaustavghosh06** [comment]
@ajhool Sorry for the late response, but yes adding it to your backend-config.json and then executing `amplify env checkout <env-name>` should resolve your issue. That way you won't loose your security type config. this was a bug long ago in @aws-amplify/cli@multienv version, but we fixed this subsequently when we moved this to the master/main CLI version.

**Comment by ajhool** [comment]
@kaustavghosh06  thanks

**Comment by ajhool** [comment]
So, I added this to my `amplify/backend/api/myapi/backend-config.json` and it is still not adding authenticationType to `aws-exports` properly in version 1.8.2

```
	"api": {
		"myapii": {
			"service": "AppSync",
			"providerPlugin": "awscloudformation",
			"authenticationType": "AMAZON_COGNITO_USER_POOLS"
		}
         }
```

I've tried `amplify env checkout myenv` and `amplify env push` and `amplify env pull --restore`

**Comment by jcardus** [comment]
> For me the problem was I had:
> 
> ```js
> import AWSAppSyncClient, { AUTH_TYPE } from 'aws-appsync'
> import aws_config from '../aws-exports'
> 
> const client = new AWSAppSyncClient({
>   url: aws_config.aws_appsync_graphqlEndpoint,
>   region: aws_config.aws_appsync_region,
>   auth: {
>     type: AUTH_TYPE.API_KEY,
>     apiKey: aws_config.aws_appsync_apiKey
>   }
> })
> ```
> 
> Fixed with:
> 
> ```js
> import AWSAppSyncClient, { AUTH_TYPE } from 'aws-appsync'
> import { Auth } from 'aws-amplify'
> import aws_config from '../aws-exports'
> 
> const client = new AWSAppSyncClient({
>   url: aws_config.aws_appsync_graphqlEndpoint,
>   region: aws_config.aws_appsync_region,
>   auth: {
>     type: AUTH_TYPE.AMAZON_COGNITO_USER_POOLS,
>     jwtToken: async () =>
>       (await Auth.currentSession()).getIdToken().getJwtToken()
>   }
> })
> ```
Thanks! Worked for me too!

**Comment by Rolando-Barbella** [comment]
I have the `"aws_appsync_graphqlEndpoint"` and the `"aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"` in my `aws-export` file.

Also did:

`
Amplify.configure(awsconfig);

Amplify.configure({
  API: {
    graphql_endpoint: 'https://my-url.appsync-api.eu-central-1.amazonaws.com/graphql',
    graphql_headers: async () => {
      const currentSession = await Auth.currentSession();
      return { Authorization: currentSession.getIdToken().getJwtToken() };
    }
  }
});
`
Same error though
