### ISSUE TITLE
@searchable throws Elasticsearch:User IllegalArgumentException

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#2639]
**Describe the bug**

I'm using AWS AppSync with `@searchable` and I did `search*` query. All of which will throw `Elasticsearch:User IllegalArgumentException` when the resource was only instantiated for the first time, i.e., I just created and I haven't done any other mutations to it (create), so the tables are currently empty.

sample query

```graphql
query {
  searchUsers {
    items {
      id
    }
    nexToken
  }
}
```

**To Reproduce**
1.  Create a resource with AWS AppSync using GraphQL.
2. Use `@searchable` with it.
3. On AppSync GraphQL UI, try to use `search*` query.

**Expected behavior**

Instead of throwing that error, it should return `items: []` which is what it normally does. (After applying the workaround specified at the bottom of this document).

**Screenshots**

![image](https://user-images.githubusercontent.com/21032419/67727819-d5403680-fa25-11e9-8c75-c0543a976e45.png)

**Desktop (please complete the following information):**

The error is not specific to any platform. You can use the AWS AppSync GraphQL UI and still be able to replicate the error.

**Smartphone (please complete the following information):**

The error is not specific to any device. You can use the AWS AppSync GraphQL UI and still be able to replicate the error.

**Additional context**

As a workaround. You can insert data to the tables first, then you can remove those data. The next time you query that table with `search` you'll get the desirable response:

```js
data: {
  searchTable: {
    items: [],
    nextToken: null
  }
}
```

**Comment by attilah** [comment]
@aprilmintacpineda I was able to reproduce this issue thanks for reporting.

**Comment by attilah** [comment]
@aprilmintacpineda could you please retry this, as I was getting back to this issue and works as you expect, perhaps it was fixed in the AppSync Service DataSource side. I asked the team and awaiting an answer.

**Comment by aprilmintacpineda** [comment]
Will get back to you. Thanks @attilah 🙇

**Comment by attilah** [comment]
@aprilmintacpineda There was a modification in the behavior of the DataSource so that can be a reason why it does not happen anymore.

**Comment by aprilmintacpineda** [comment]
Hi @attilah,

Sorry for the delay on feedback. I just had the chance to get back to the project assigned to me that was using this. So here's the scenario:

The project I have that's experiencing this already have an existing UAT environment setup, I just checked it out and it's still experiencing the error. It was previously using `@aws-amplify/cli@3.17.0` but I have just upgraded it to `4.13.1` and the error still occurs. Is there any prerequisites for me to get the fix? or will it just be applied the next time I create a new environment?
