### ISSUE TITLE
UndeterminedEnvironmentError when deploying with amplifyPush

### ISSUE THREAD

**Issue by mdlavin** [aws-amplify/amplify-cli#3094]
When deploying with Amplify 4.9.0 from the Amplify Console deploy pipline, I see the following error:

```
{ UndeterminedEnvironmentError: Current environment cannot be determined
Use 'amplify init' in the root of your app directory to initialize your project with Amplify
   at getEnvInfo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/get-env-info.js:19:15)
   at AmplifyToolkit.getProjectDetails [as _getProjectDetails] (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/get-project-details.js:14:26)
   at Object.run (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/amplify-service-migrate.js:9:42)
   at Object.run (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js:80:33)
   at process._tickCallback (internal/process/next_tick.js:68:7)
   at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
   at startup (internal/bootstrap/node.js:283:19)
   at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3) name: 'UndeterminedEnvironmentError' }
```

It appears that the code in some Amplify console migration code is not setup to run before the amplify/.config/local-env-info.json is created

**Comment by mdlavin** [comment]
To workaround the issue, I added the following script before the `amplifyPush --simple` command:

```bash
echo "{ \"projectPath\": \"$(pwd)\", \"envName\": \"${AWS_BRANCH}\"}" > amplify/.config/local-env-info.json
```

**Comment by orland1to** [comment]
i have the same problem, it was fixed adding 
```
- nvm use $VERSION_NODE_10
 - npm install -g @aws-amplify/cli@4.1.1
```
before 
`- amplifyPush --simple`
in build settings.

**Comment by heitorlessa** [comment]
Do you mean 4.11? I've just downgraded from 4.12 to 4.11 and worked. 

**excerpt amplify.yml**

```yaml
version: 0.1
backend:
  phases:
    preBuild:
      commands:
        - npm install -g @aws-amplify/cli@4.11.0 # pinned known working version
```

**Comment by kaustavghosh06** [comment]
The fix for this issue has been pushed out in the latest version of the CLI >=4.13.1

**Comment by cyrfer** [comment]
@kaustavghosh06 @UnleashedMind  I still see this error, using 

```bash
npm list -g --depth=0
myuserpath/.nvm/versions/node/v13.2.0/lib
├── @aws-amplify/cli@4.13.4
└── npm@6.13.1

git clone ... myrepo
cd myrepo
git checkout dev
npm install
amplify env checkout dev

Current environment cannot be determined
Use 'amplify init' in the root of your app directory to initialize your project with Amplify
UndeterminedEnvironmentError: Current environment cannot be determined
Use 'amplify init' in the root of your app directory to initialize your project with Amplify
    at getEnvInfo (myuserpath/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/get-env-info.js:18:15)
    at Object.run (myuserpath/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/checkout.js:17:30)
    at Object.run (myuserpath/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/lib/commands/env.js:25:37)
    at Object.executeAmplifyCommand (myuserpath/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/lib/index.js:94:25)
    at executePluginModuleCommand (myuserpath/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:47:32)
    at async Object.executeCommand (myuserpath/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:15:9)
    at async Object.run (myuserpath/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/lib/index.js:41:9)

```
