### ISSUE TITLE
nextToken not accepted and gives error "Invalid pagination token given"

### ISSUE THREAD

**Issue by apanagos** [aws-amplify/amplify-cli#3411]
**Describe the bug**
Query is working in development and build environments but when deployed in the Test environment the nextToken is never accepted.

The same error occurs in the code as well as the AppSync console where we do a query with a limit and get a nextToken. Then we do a query straight away with the same token and it gives the following error:
com.amazonaws.deepdish.common.pagination.InvalidPaginationTokenException: Invalid pagination token given.

**To Reproduce**
Do following query in the console (same as in the code) FYI There are 15 items in the table.

```
{
  listUsers(limit:3){
    items{
      name
    }
    nextToken
  }
}
```
The response is:
```
{
  "data": {
    "listUsers": {
      "items": [
        {
          "name": "Joergen Von Klopp"
        },
        {
          "name": "Yolanda McAdams"
        },
        {
          "name": "Info Test"
        }
      ],
      "nextToken": "eyJ2ZX...shortened="
    }
  }
}
```
Then we do it again with the nextToken:
```
{
  listUsers(limit:3,nextToken:"eyJ2ZX...shortened="){
    items{
      name
    }
    nextToken
  }
}
```
The error is:
```
{
  "data": {
    "listUsers": null
  },
  "errors": [
    {
      "path": [
        "listUsers"
      ],
      "data": null,
      "errorType": "DynamoDB:UserIllegalArgumentException",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "com.amazonaws.deepdish.common.pagination.InvalidPaginationTokenException: Invalid pagination token given."
    }
  ]
}

```

We experience the same behavior with all the tables in this environment. If we increase the limit we of course get all the elements but for some reason nextToken does not work.

**Expected behavior**
Should get more data returned like on the other environments.

**Screenshots**

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
npx: installed 1 in 1.301s

  System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 8.41 GB / 23.94 GB
  Binaries:
    Node: 12.13.1 - C:\Tools\nodejs\node.EXE
    npm: 6.13.2 - C:\Tools\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
    Internet Explorer: 11.0.18362.1

```

</details>

**Additional context**
Amplify --version 4.5.0
"aws-amplify": "^2.2.2",
"aws-amplify-react": "^3.1.3",

**Comment by nick-secur** [comment]
We are having a similar issue. We have a react.js / amplify app with a "master - detail" view where we paginate through records from an aws dynamo db using the 'next token' property returned from a graphQl 'list all' query. The app was working great until we tried to set up a team dev environment with continuous deploys pulling from a git repo. All queries seem to be working well from the new environments with the exception of the 'next token' returned from the list all query ...

**Comment by apanagos** [comment]
Thanks @AaronHarris , we have 6 environments, 

1. 2 **DEV** environments,
2. a nightly **BUILD** env,
3. a **TEST** env
4. and a **PROD** env.

We merged from DEV -> BUILD -> TEST and this broke in TEST,
It works in DEV and BUILD but not TEST with the token error. FYI TEST worked before the merge and now ALL tables in TEST have the same issue.

Here is Query.listUsers.req.vtl  for both DEV and TEST. They are the same.
```
#set( $limit = $util.defaultIfNull($context.args.limit, 10) )
#set( $ListRequest = {
  "version": "2017-02-28",
  "limit": $limit
} )
#if( $context.args.nextToken )
  #set( $ListRequest.nextToken = "$context.args.nextToken" )
#end
#if( $context.args.filter )
  #set( $ListRequest.filter = $util.parseJson("$util.transform.toDynamoDBFilterExpression($ctx.args.filter)") )
#end
#if( !$util.isNull($modelQueryExpression)
                        && !$util.isNullOrEmpty($modelQueryExpression.expression) )
  $util.qr($ListRequest.put("operation", "Query"))
  $util.qr($ListRequest.put("query", $modelQueryExpression))
  #if( !$util.isNull($ctx.args.sortDirection) && $ctx.args.sortDirection == "DESC" )
    #set( $ListRequest.scanIndexForward = false )
  #else
    #set( $ListRequest.scanIndexForward = true )
  #end
#else
  $util.qr($ListRequest.put("operation", "Scan"))
#end
$util.toJson($ListRequest)

```

**Comment by a-j-olly** [comment]
I am also coming across this error when using next token for pagination. This seems to have began after I pushed to my development environment the same day this ticket was raised (The error wasn't spotted until today). This push included a two field change to a table in my graphql schema, where said fields had their type changed from '[String]!' to 'AWSJSON!'. Interestingly, the now failing query that uses next token for pagination reads from a different table than that which was changed.

I am using Cognito user groups for authentication, and I can provide full schema if necessary.

Here is the error that I have captured in the AppSync console:

```
{
  "data": {
    "articlesByDate": null
  },
  "errors": [
    {
      "path": [
        "articlesByDate"
      ],
      "data": null,
      "errorType": "DynamoDB:UserIllegalArgumentException",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "com.amazonaws.deepdish.common.pagination.InvalidPaginationTokenException: Invalid pagination token given."
    }
  ]
```

And here is the query req vtl in question (not quite as tidy as the gentleman above):

```
## [Start] Set query expression for @key **
#set( $modelQueryExpression = {} )
## [Start] Validate key arguments. **
#if( !$util.isNull($ctx.args.datePublished) && $util.isNull($ctx.args.dataType) )
  $util.error("When providing argument 'datePublished' you must also provide arguments dataType", "InvalidArgumentsError")
#end
## [End] Validate key arguments. **
#if( !$util.isNull($ctx.args.dataType) )
  #set( $modelQueryExpression.expression = "#dataType = :dataType" )
  #set( $modelQueryExpression.expressionNames = {
  "#dataType": "dataType"
} )
  #set( $modelQueryExpression.expressionValues = {
  ":dataType": {
      "S": "$ctx.args.dataType"
  }
} )
#end
## [Start] Applying Key Condition **
#if( !$util.isNull($ctx.args.datePublished) && !$util.isNull($ctx.args.datePublished.beginsWith) )
  #set( $modelQueryExpression.expression = "$modelQueryExpression.expression AND begins_with(#sortKey, :sortKey)" )
  $util.qr($modelQueryExpression.expressionNames.put("#sortKey", "datePublished"))
  $util.qr($modelQueryExpression.expressionValues.put(":sortKey", { "S": "$ctx.args.datePublished.beginsWith" }))
#end
#if( !$util.isNull($ctx.args.datePublished) && !$util.isNull($ctx.args.datePublished.between) )
  #set( $modelQueryExpression.expression = "$modelQueryExpression.expression AND #sortKey BETWEEN :sortKey0 AND :sortKey1" )
  $util.qr($modelQueryExpression.expressionNames.put("#sortKey", "datePublished"))
  $util.qr($modelQueryExpression.expressionValues.put(":sortKey0", { "S": "$ctx.args.datePublished.between[0]" }))
  $util.qr($modelQueryExpression.expressionValues.put(":sortKey1", { "S": "$ctx.args.datePublished.between[1]" }))
#end
#if( !$util.isNull($ctx.args.datePublished) && !$util.isNull($ctx.args.datePublished.eq) )
  #set( $modelQueryExpression.expression = "$modelQueryExpression.expression AND #sortKey = :sortKey" )
  $util.qr($modelQueryExpression.expressionNames.put("#sortKey", "datePublished"))
  $util.qr($modelQueryExpression.expressionValues.put(":sortKey", { "S": "$ctx.args.datePublished.eq" }))
#end
#if( !$util.isNull($ctx.args.datePublished) && !$util.isNull($ctx.args.datePublished.lt) )
  #set( $modelQueryExpression.expression = "$modelQueryExpression.expression AND #sortKey < :sortKey" )
  $util.qr($modelQueryExpression.expressionNames.put("#sortKey", "datePublished"))
  $util.qr($modelQueryExpression.expressionValues.put(":sortKey", { "S": "$ctx.args.datePublished.lt" }))
#end
#if( !$util.isNull($ctx.args.datePublished) && !$util.isNull($ctx.args.datePublished.le) )
  #set( $modelQueryExpression.expression = "$modelQueryExpression.expression AND #sortKey <= :sortKey" )
  $util.qr($modelQueryExpression.expressionNames.put("#sortKey", "datePublished"))
  $util.qr($modelQueryExpression.expressionValues.put(":sortKey", { "S": "$ctx.args.datePublished.le" }))
#end
#if( !$util.isNull($ctx.args.datePublished) && !$util.isNull($ctx.args.datePublished.gt) )
  #set( $modelQueryExpression.expression = "$modelQueryExpression.expression AND #sortKey > :sortKey" )
  $util.qr($modelQueryExpression.expressionNames.put("#sortKey", "datePublished"))
  $util.qr($modelQueryExpression.expressionValues.put(":sortKey", { "S": "$ctx.args.datePublished.gt" }))
#end
#if( !$util.isNull($ctx.args.datePublished) && !$util.isNull($ctx.args.datePublished.ge) )
  #set( $modelQueryExpression.expression = "$modelQueryExpression.expression AND #sortKey >= :sortKey" )
  $util.qr($modelQueryExpression.expressionNames.put("#sortKey", "datePublished"))
  $util.qr($modelQueryExpression.expressionValues.put(":sortKey", { "S": "$ctx.args.datePublished.ge" }))
#end
## [End] Applying Key Condition **
## [End] Set query expression for @key **
#set( $limit = $util.defaultIfNull($context.args.limit, 10) )
#set( $QueryRequest = {
  "version": "2017-02-28",
  "operation": "Query",
  "limit": $limit,
  "query": $modelQueryExpression,
  "index": "byDate"
} )
#if( !$util.isNull($ctx.args.sortDirection)
                    && $ctx.args.sortDirection == "DESC" )
  #set( $QueryRequest.scanIndexForward = false )
#else
  #set( $QueryRequest.scanIndexForward = true )
#end
#if( $context.args.nextToken ) #set( $QueryRequest.nextToken = "$context.args.nextToken" ) #end
#if( $context.args.filter ) #set( $QueryRequest.filter = $util.parseJson("$util.transform.toDynamoDBFilterExpression($ctx.args.filter)") ) #end
$util.toJson($QueryRequest)
```
And the res vtl:
`$util.toJson($ctx.result)`

Has anyone rebuilt their environment from scratch to see if this fixes it? I would prefer not to have to do this, but when in doubt...

**Comment by apanagos** [comment]
I am waiting a week or so before I blow my test away and rebuild. I am hoping we can figure out a resolution because go live is coming quick and I cannot be rebuilding a production environment. It has taken a while to stabilize the Amplify environments and make sure everything is done in a certain order so env don't get blown up.

**Comment by malcomm** [comment]
Just a bit of info, I was running into this as well after I upgraded from amplify-cli 4.13.1 to 4.13.2. Once I downgraded to 4.13.1 and did another `amplify push` life was better.

**Comment by mightiesthero** [comment]
Thank you @malcomm

**Comment by olivoil** [comment]
Having the same issue with the latest CLI version (4.13.3) on any @model list query. Forcing version 4.13.1 of the CLI in build settings -> Live package updates does not seem to solve it for me, at least for existing `@model`s.

It happens with any `@model`, and is reproducible directly from the AppSync Console.

Generate a simple @model

```graphql
type Todo @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  owner: ID!
  text: String
  checked: Boolean
}
```

Create a few objects, and query them, copying the value of nextToken verbatim from a previous query directly in AppSync Console

```graphql
query ListTodos {
  listTodos(limit: 2, nextToken: "ey...SRiJ9") {
    items {
      id
      text
      checked
    }
    nextToken
  }
}
```

The error shows up consistently

```json
{
  "data": {
    "listTodos": null
  },
  "errors": [
    {
      "path": [
        "listTodos"
      ],
      "data": null,
      "errorType": "DynamoDB:UserIllegalArgumentException",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "com.amazonaws.deepdish.common.pagination.InvalidPaginationTokenException: Invalid pagination token given."
    }
  ]
}
```

**Comment by a-j-olly** [comment]
@malcomm For me, this issue was occurring on CLI version 4.13.1, however once I downgraded to 4.13.0 it cleared up. I did try and upgrade to 4.13.2 to see if that might be a fix, but I could still reproduce the error.

@olivoil I'd recommend taking the CLI down to 4.13.0 and then doing a `amplify push` and see if that works.

Hopefully the Amplify team can get to the bottom of this, but I have a work around for now.

**Comment by apanagos** [comment]
@a-j-olly I am on Amplify 4.5.0 and I haven't upgraded for a while, so there were no environment changes. Though saying that the problem I am having is with an environment that is built by "AWS Amplify" from GIT. I assume they would be using the latest version of Amplify when building the backend. I will add an echo to the amplify.yml to see what version they are using.
BUT saying that my build environment is also built by "AWS Amplify" so I would expect the same issue if it was a version issue. But BUILD works (and the DEV environments I built by hand work) but TEST does not.

**Comment by dtelaroli** [comment]
+1 same problem with @key and custom queryField.

**Comment by SwaySway** [comment]
Hi @apanagos 
I'm trying to reproduce this though I'm not able to
this is the schema I am trying on version 4.5.0
```gql
type Todo @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  owner: ID!
  text: String
  checked: Boolean
} 
```

I'm running this in `us-west-2`.

If possible could you provide the schema you are using, here or email amplify-cli@amazon.com, and provide the region this api exists.

**Comment by apanagos** [comment]
Hi @SwaySway, problem is that I am experiencing the problem with all the tables in my TEST environment.

Here is a simple one that is causing issues:

```graphql
type Tags @model @aws_cognito_user_pools @aws_iam{
  id:ID!
  tag:String!
} 

```
I am running this in us-east-1

Let me go through the process of how I promote in case the problem is there.

```batchfile
git checkout test
git merge build
amplify env checkout testedge
amplify env pull
amplify push

```
once its is finished i do the following:

```
git add *
git commit -m "upgrade"
git push
```

Then the build automatically starts in "AWS Amplify" as I have set it up to build from updating the branch.

Some other things to take into account.

My command shell has amplify at version 4.5.0
BUT when it builds in "AWS Amplify" I guess it uses the latest version of Amplify CLI?

Just a little more info. I follow the same procedure above for my other environments.

e.g.
```
git checkout build
git pull
git merge dev
amplify env checkout buildaaa
amplify env pull
amplify push
git add *
git commit -m "update"
git push

```
One last piece of information. The follwoing is the build file I have checked into GIT and is used to build in "AWS Amplify"

file: amplify.yml

```yaml
version: 0.5
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - echo "User $USER_BRANCH"
        - echo "AWS User $AWS_BRANCH"
        - amplifyPush --environment $USER_BRANCH --simple
frontend:
  phases:
    preBuild:
      commands:
        - echo "Front End Prebuild"
        - npm install --global gulp-cli
        - npm ci
    build:
      commands:
        - gulp
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

```

If you need anything else, please just reach out and I will help as much as i can.

Thanks

**Comment by slatemates** [comment]
I have tried deploying a test api through both  Amplify Version(4.13.3 and 4.13.2) with the following schema :

type TODO @model {
  id: ID!
  amount : Int!
}


The resolver generated using amplify CLI 

Query.listTODOs.req.vtl


#set( $limit = $util.defaultIfNull($context.args.limit, 10) )
#set( $ListRequest = {
  "version": "2017-02-28",
  "limit": $limit
} )
#if( $context.args.nextToken )
  #set( $ListRequest.nextToken = $util.toJson($context.args.nextToken) )
#end
#if( $context.args.filter )
  #set( $ListRequest.filter = $util.parseJson("$util.transform.toDynamoDBFilterExpression($ctx.args.filter)") )
#end
#if( !$util.isNull($modelQueryExpression)
                        && !$util.isNullOrEmpty($modelQueryExpression.expression) )
  $util.qr($ListRequest.put("operation", "Query"))
  $util.qr($ListRequest.put("query", $modelQueryExpression))
  #if( !$util.isNull($ctx.args.sortDirection) && $ctx.args.sortDirection == "DESC" )
    #set( $ListRequest.scanIndexForward = false )
  #else
    #set( $ListRequest.scanIndexForward = true )
  #end
#else
  $util.qr($ListRequest.put("operation", "Scan"))
#end
$util.toJson($ListRequest)



We keep getting the same error even when running queries  with Appsync console directly . This issue needs to be addressed urgently . Proper testing must be ensured before releasing new 
 versions.

**Comment by clodal** [comment]
As per @a-j-olly's [comment](https://github.com/aws-amplify/amplify-cli/issues/3411#issuecomment-586160577) above, can confirm it works when I downgraded the cli from `4.13.2` to `4.13.0` and do `amplify push`.

**Comment by a-j-olly** [comment]
Just an update. 

Having downgraded to 4.13.0 and finding success, I was annoyed to find out this morning that once again the problem has cropped up. I have not made any alterations whatsoever since I did the downgrade and `amplify push`.

I'm getting the same error: 

```
{
  "data": {
    "articlesByDate": null
  },
  "errors": [
    {
      "path": [
        "articlesByDate"
      ],
      "data": null,
      "errorType": "DynamoDB:UserIllegalArgumentException",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "com.amazonaws.deepdish.common.pagination.InvalidPaginationTokenException: Invalid pagination token given."
    }
  ]
}
```

Pagination is a critical feature of GraphQL. Fixing this issue is of vital importance.
If you need anymore info see my above posts or PM me.

**Comment by grigull** [comment]
I ran into the same problem when I went to 4.13.3, downgraded to 4.13.1 which still works for me.

**Comment by a-j-olly** [comment]
So I just did another 'empty' push, and it has cleared up again. I think I'm just going to take a break...

**Comment by kaustavghosh06** [comment]
We've root-caused the issue with the latest release and working on a fix for this which will be released soon.
cc: @attilah

**Comment by dimonchik-com** [comment]
Have the same problem 
`com.amazonaws.deepdish.common.pagination.InvalidPaginationTokenException: Invalid pagination token given.`

**Comment by AshwiniRaysecur** [comment]
I attempted to build the application again from scratch, and still getting the pagination error for Amplify version 4.13.3

The resolver generated 'Query.listSecurSamples.req.vtl' file:

#set( $limit = $util.defaultIfNull($context.args.limit, 10) )
#set( $ListRequest = {
  "version": "2017-02-28",
  "limit": $limit
} )
#if( $context.args.nextToken )
  #set( $ListRequest.nextToken = "$context.args.nextToken" )
#end
#if( $context.args.filter )
  #set( $ListRequest.filter = $util.parseJson("$util.transform.toDynamoDBFilterExpression($ctx.args.filter)") )
#end
#if( !$util.isNull($modelQueryExpression)
                        && !$util.isNullOrEmpty($modelQueryExpression.expression) )
  $util.qr($ListRequest.put("operation", "Query"))
  $util.qr($ListRequest.put("query", $modelQueryExpression))
  #if( !$util.isNull($ctx.args.sortDirection) && $ctx.args.sortDirection == "DESC" )
    #set( $ListRequest.scanIndexForward = false )
  #else
    #set( $ListRequest.scanIndexForward = true )
  #end
#else
  $util.qr($ListRequest.put("operation", "Scan"))
#end
$util.toJson($ListRequest)

```
Worked correctly after downgrading to Amplify version 4.13.0

**Comment by kaustavghosh06** [comment]
Could you please try this out with 4.13.4? We fixed this in our latest version

**Comment by nick-secur** [comment]
@kaustavghosh06 Please note we  (i.e., myself and @AshwiniRaysecur )have tested publishing our app with version 4.13.4 and the issue seems to be resolved. Smoke tests show our app once again behaves as expected.

**Comment by malcomm** [comment]
I just upgraded to version 4.13.4 and things appear to be working for me as well. I'll keep folks posted if otherwise. Thanks!

**Comment by apanagos** [comment]
We tested it today and I can confirm that the fix does work. Thank you @kaustavghosh06 , @SwaySway , @AaronHarris , @sammartinez , @yuth , @attilah for addressing the issue so quickly.
Now I have made some changes to our process. I changed "AWS Amplify" to not use the latest version of Amplify but to use a versioned (4.13.4) so it is in-sync with what we are developing with. As we upgrade and test our version of Amplify then we will change the "AWS Amplify" version so we are not surprised.
Thanks Again.

**Comment by slatemates** [comment]
Upgraded to 4.13.4 . The issue is resolved .Thanks

**Comment by oliverandersencox** [comment]
This is still happening for me on  4.13.4

**Comment by SwaySway** [comment]
@oliverandersencox Are you using `@key` with your query?

**Comment by oliverandersencox** [comment]
@SwaySway yes I am

**Comment by SwaySway** [comment]
@oliverandersencox Could you try the workaround mentioned in #3493?
If it is related to that please follow that issue for updates.

**Comment by rarira** [comment]
> This is still happening for me on 4.13.4

same here, downgraded to 4.13.1 and it works

**Comment by WerewolFox** [comment]
I just wanted to confirm that I had this issue with 4.13.3 but upgrading to 4.13.4 resolve it for me.  The steps I took were:
- npm install -g @aws-amplify/cli@latest
- make a simple change to the schema (I added a field)
- amplify api gql-compile
- amplify push
That was it.. works fine now.. thanks guys.

**Comment by mithunkalan** [comment]
@WerewolFox 
Same problem. same fix. 
Except that i didnt need amplify api gql-compile

**Comment by philateatclub** [comment]
> I just wanted to confirm that I had this issue with 4.13.3 but upgrading to 4.13.4 resolve it for me. The steps I took were:
> 
> * npm install -g @aws-amplify/cli@latest
> * make a simple change to the schema (I added a field)
> * amplify api gql-compile
> * amplify push
>   That was it.. works fine now.. thanks guys.

I had the same issue. However I was on Amplify --version 4.13.4. Bumped it to the latest --version 4.17.1.

• amplify api gql-compile
• amplify push

That fixed it for me!

**Comment by tomasyaya** [comment]
Hello @SwaySway 
I'm having this issue even when I try the query from the Appsync console.
My type is NOT using the @key directive.
I'm using the latest Amplify CLI 4.17.2
Could you please address my issue?
Thank you!

**Comment by PrometheanGeethika** [comment]
Hello,
This issue is back with the latest (4.18.1) Amplify CLI Version. Overriding the version with 4.16.1 (which is the one I happen to know is working) as described at https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup-live-updates no longer throws this error.

**Comment by iShavgula-TacTill** [comment]
Hello, 
I'm having this issue with amplify 4.25.0.

**Comment by ohsik** [comment]
I'm having this issue too with 4.18.1

**Comment by lqthaiegi** [comment]
I have the same issue. I'm using version 4.13.4. Base on some comments above I upgraded to 4.27.3, it works fine for me.

**Comment by iShavgula-TacTill** [comment]
I'm still having this issue, v: 4.29.7.
It has been months, impossible to to use Amplify in production 👎

**Comment by SwaySway** [comment]
Hello @iShavgula-TacTill 
Could you provide a schema which can reproduce this scenario?

**Comment by iShavgula-TacTill** [comment]
Thank you for having a look at this.

This happens for every DynamoDB `Query` (**2018-05-29**) which goes via Pipeline Resolvers and uses GSI.
I tried to delete and recreate the these queries many times, but that does not help, it can be reproduced every time with every query following these patterns. Here is a (pseudo) code :
```
#set( $QueryRequest = {
  "version": "2018-05-29",
  "operation": "Query",
  "limit": $limit,
  "query": some expression,
  "index": "index name"
} )
#if( !$util.isNull($ctx.args.sortDirection) && $ctx.args.sortDirection == "DESC" )
  #set( $QueryRequest.scanIndexForward = false )
#else
  #set( $QueryRequest.scanIndexForward = true )
#end
#if( $context.args.nextToken ) 
  #set( $QueryRequest.nextToken = $util.toJson($context.args.nextToken) ) 
#end
#if( $context.args.filter ) 
  #set( $QueryRequest.filter = $util.parseJson("$util.transform.toDynamoDBFilterExpression($ctx.args.filter)") ) 
#end
$util.toJson($QueryRequest)
```

Please let me know if you need more information.

P.S. I did check that nextToken is correctly used in my pipelines, it was working fine until it just stopped working after one of the Amplify cli updates.

**Comment by SwaySway** [comment]
@iShavgula-TacTill 
Currently the CLI does not support pipeline resolvers. Do you have pipeline resolvers setup by overriding the generated resolvers? If so the fix you could apply here is to change the query resolver to remove `$util.toJson()`. This is what the transformer currently generates for query resolvers that use `nextToken`.
```
#if( $context.args.nextToken ) 
  #set( $QueryRequest.nextToken = $context.args.nextToken ) 
#end
```

**Comment by iShavgula-TacTill** [comment]
That fix did work, but I find that very strange because of couple of reasons :
- I had some auto-generated queries which used `toJSON()` for `nextToken` before commenting on this issue.
- I have not changed DynamoDB `Query` version

Could that be linked to AppSync utilities' updates ? 
Any tips how to avoid this kind of issues ?

Thank you

**Comment by yuth** [comment]
In an earlier version of the Amplify CLI a bug was introduced which double encoded the payload toJSON. What I suspect is you might have overridden the template when the CLI had the bug, which got you the buggy resolver. This was fixed in the CLI later, but since the template was overriden, that fix not propagate to that template.
