### ISSUE TITLE
amplify init stuck after choosing editor

### ISSUE THREAD

**Issue by aldarund** [aws-amplify/amplify-cli#355]
**Describe the bug**

**To Reproduce**
amplify init  and then choose any editor ( doesnt matter which, result is same)

**Expected behavior**
obv init project, continue with other questions etc

**Screenshots**
https://i.imgur.com/wXyfkeO.png

**Desktop (please complete the following information):**
 - OS:  Windows 10 x64
Node 11
```
amplify -v
0.1.29
```

**Comment by bright-sea** [comment]
Same with me. Window 7 enterprise edition, Node10   amplify 0.1.29

**Comment by yuth** [comment]
@aldarund Currently amplify-cli needs WSL to work. Could you try with WSL

**Comment by aldarund** [comment]
hm. why it cant work on win without wsl?
amplify configure worked fine.

**Comment by yuth** [comment]
amplify uses [Gluegun](https://github.com/infinitered/gluegun) and gluegun doesn't work well in windows without WSL. We have opened an [issue](https://github.com/infinitered/gluegun/issues/384) with them.

**Comment by VetBoard** [comment]
This is happening to me too. I have installed WSL, but still doesnt work. Any idea?

**Comment by VetBoard** [comment]
I'm sorry but there is no error... it just stuck there, with the cursor blinking, but nothing happens just after I select the editor.

**Comment by aldarund** [comment]
Yes, there no error stack trace. It just stuck doing nothing as in screenshot in my initial message

**Comment by pt7892** [comment]
Same issue here, stuck on selecting default editor

**Comment by attilah** [comment]
I was pretty frustrating and I spent some time to look into it. This issue is caused by inquerier component.

Unfortunately amplify-cli is not using the same version of all the dependencies. CLI itself using 3.2.1 and it has this issue, from 5.0.0 it is fixed.

I tried the inquerier versions 1 by 1 and 5.0.0 is the first one which runs their pizza example well, all the others are stuck after printing the json.

Internally the main reason is the setRawMode call to stdio's handle in readline module, my guess is that some pieces were not closed properly and TTY got into an invalid state.

If someone could create a PR, all you've to do is to move all the packages.json from ^3.2.1 to ^6.0.0 for the inquerier component so that would be the same for all modules ;-)

**Comment by bghtrbb** [comment]
This has not fixed the issue. I have clean installed these and am still not able to run the commands.

![Amplify Config](https://s3.amazonaws.com/otherrandomfiles/amplify+config.PNG)
![Amplify Init](https://s3.amazonaws.com/otherrandomfiles/amplify+init.PNG)
