### ISSUE TITLE
Elasticsearch Creation Fails due to name length

### ISSUE THREAD

**Issue by mwarger** [aws-amplify/amplify-cli#566]
**Describe the bug**
I get this error when creating the elasticsearch for a GraphQL API with a @searchable directive.

1 validation error detected: Value 'DynamoDBToElasticSearchFunction-p7gynnfosbettdoceeqj43qaii-develop' at 'functionName' failed to satisfy constraint: Member must have length less than or equal to 64 (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: a5bd0b54-fb52-11e8-84ba-4d1bb5abfc41)

**To Reproduce**
i'm not sure what led to this problem.

**Expected behavior**
Hopefully these names can be checked so that they don't result in this error.  

IMHO, DynamoDBToElasticSearchFunction-p7gynnfosbettdoceeqj43qaii is a bit verbose.  
DynamoDBToElasticSearchFunction probably isn't necessary - could be shortened, I think.
I'm not sure if p7gynnfosbettdoceeqj43qaii or if it's derived from some other part of the API, but it's a bit long as well.

Thanks for all your help!

**Comment by mikeparisstuff** [comment]
Thanks for reporting this issue, I have recorded it and it will get picked up as soon as possible. The relevant code to update is https://github.com/aws-amplify/amplify-cli/blob/22e987295837c584736453ab7f5b219f240c0b52/packages/graphql-elasticsearch-transformer/src/resources.ts#L134 and I would also be happy to review a PR :). You should be able to customize the name via the parameter as well.

**Comment by eelzinaty** [comment]
I had this issue before, and I think it starts to occur when using amplify multi-environment cli. You can avoid that by choosing environment name that is less than five characters.

**Comment by npradeeptha** [comment]
I got the same error and my env name was "master"

**Comment by wbroek** [comment]
Got hit by this today as wel, solved it for now to set a short name (max 5 characters) in `ElasticSearchStreamingFunctionName` in the `parameters.json`

@mikeparisstuff how does one make a good PR; of course I can fork the repo; change code and submit a PR, but I mean how do you solve it the right way (like truncate the name if longer then 64, what part is important in the name, etc) and how do I test it in a good manner

**Comment by jesse-bonzo** [comment]
Setting `ElasticSearchStreamingFunctionName` in `parameters.json` does not work for me. Any changes I make to `parameters.json` are lost. I believe this change is the cause c8fdbff.

**Comment by UnleashedMind** [comment]
@jesse-bonzo @wbroek 
what's the version of your cli?

**Comment by jesse-bonzo** [comment]
Mine is 0.2.1-multienv.11, which I think is a little behind the mainline.

**Comment by UnleashedMind** [comment]
Could you please try to update to the latest of the multienv?  0.2.1-multienv.15, see if it resolves your issue.

**Comment by jesse-bonzo** [comment]
@UnleashedMind 0.2.1-multienv.15 does deploy the stack with no errors, however now the appsync API name is missing the environment name.

**Comment by kaustavghosh06** [comment]
@jesse-bonzo Where are you checking for the API name? Did you check the AppSync console or the parameters.json file?

**Comment by jesse-bonzo** [comment]
@kaustavghosh06 I'm checking the resulting resources that are created. For instance, the dynamodb tables and the AppSync API name. When I use `amplify push` on my local machine, the resources are created without the environment name suffix, which is not expected. When I push my changes and build within the Amplify Console, the resources are created with the environment suffix except in this case the Lambda ElasticSearch name is too long and the stack fails to completely build and is rolled back.

**Comment by kaustavghosh06** [comment]
@jesse-bonzo I'm taking a look at it right now.

**Comment by kaustavghosh06** [comment]
@jesse-bonzo Could you take a look at my response in #631?

I wasn't able to reproduce the issue with the the latest version of the CLI.
Did you by any chance mess around with your parameters.json in the amplify/backend/<api-name>/ directory?

**Comment by kaustavghosh06** [comment]
@jesse-bonzo Does it also fail when you do amplify push using the CLI? I was able to create the API with @searchable using the CLI with an env name of `mylongenv`. 
As for the Amplify console team, I'll engage with them to update the version of CLI they are using on their end. That should mediate the issue with the Amplify console.

**Comment by kaustavghosh06** [comment]
@jesse-bonzo Sorry, you're right, the ElasticSearchStreamingLambdaFunction resource creation still fails due to the naming constraints. I'm taking a look at it.

**Comment by kaustavghosh06** [comment]
@jesse-bonzo @mwarger We published a new version of the CLI (0.2.1-multienv.17) with a fix for the naming issue (#635)

**Comment by kaustavghosh06** [comment]
@jesse-bonzo  Also, I've notified the Amplify console team to update the CLI version on their end to avoid build issues. They'll be rolling out the change soon.

**Comment by jesse-bonzo** [comment]
@kaustavghosh06 Thanks for your help!

**Comment by mwarger** [comment]
@kaustavghosh06 Thanks!  I will update and give this a shot.

**Comment by mwarger** [comment]
@kaustavghosh06 This appears to not be working, and updating the parameters.json file doesn't appear to fix it.  Did this not get deployed?

**Comment by mwarger** [comment]
@kaustavghosh06 
I just pushed to the amplify console and this still failed for the same reason.  

```
1 validation error detected: Value 'DynamoDBToElasticSearchFunction-ofrev3hk2fefjbvyqk2rfb26ri-develop' at 'functionName' failed to satisfy constraint: Member must have length less than or equal to 64 (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: e5d10435-0d17-11e9-a812-d1ad551d6bd2)
```

My local dev stack was able to be created successfully, even before this latest update.  

I am a little concerned that the console is possibly ever running an out-of-date version - would easily lead to confusion like this when I can have an environment working, but then the same thing doesn't work when I push to a remote.

Can the console be updated so I can try again by re-building?  Please let me know.  Thanks!

**Comment by kaustavghosh06** [comment]
@mwarger I’ve communicated this is to the console team to update the CLI on their end. I’ll update this issue after a successful deploymen.

**Comment by mwarger** [comment]
@kaustavghosh06 It appears that the console was updated - that latest deploy worked.  Thanks!
