### ISSUE TITLE
Amplify push fails with Connection timed out after 120000ms

### ISSUE THREAD

**Issue by kimfucious** [aws-amplify/amplify-cli#5663]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I just upgraded amplify cli to 4.30.0, from a few versions back, and now I am unable to perform an `amplify push` that I was able to do prior to the upgrade.

The following error is thrown:
```console
Connection timed out after 120000ms
An error occurred during the push operation: Connection timed out after 120000ms
```
**Amplify CLI Version**
4.30.0

**To Reproduce**
Upgrade to v 4.30.0
Run and amplify push

**Expected behavior**
It should push without an error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 (PowerShell)
 - Node Version: v12.18.3

**Additional context**
I'm gonna start rolling back to old versions, but it would be nice to know how to resolve this; thanks.

**Comment by kimfucious** [comment]
FYI: rolling back to 4.26.0 got me back to pushability...  I'll forward until it breaks and report back, time-permitting.

**Comment by nikhname** [comment]
Hi @kimfucious, do you have lambda layers configured in your project?

**Comment by kaustavghosh06** [comment]
@kimfucious Curious to know if there any other operation logs pre the connection timeout error. Did the CloudFormation deployment even start?

**Comment by kimfucious** [comment]
> Hi @kimfucious, do you have lambda layers configured in your project?

Hi @nikhname, thanks for the quick response.  I do not have lambda layers configured for this project.

**Comment by kimfucious** [comment]
> @kimfucious Curious to know if there any other operation logs pre the connection timeout error. Did the CloudFormation deployment even start?

Hi @kaustavghosh06, thanks for the follow up.

The process starts as normal, and asks (Y/N) if you want to do the push.

Then, and this was new with 4.30.0, I got a little spinner that said, "Uploading files 90%".

It stays like that for a while, (probably 2 mins/120K ms, I didn't time it), and then it throws the error noted above with nothing else logged to the console.

Please let me know if/how I can provide more info, if you need it.

**Comment by kimfucious** [comment]
Hi @kaustavghosh06 & @nikhname,

This may be a non-issue.  I upped the version incrementally from 4.26.0, doing pushes along the way.

And when I just pushed while on v.4.30.0, it worked without error.

I'll work with v.4.30.0 for a while to see if the issue presents itself, and will report back here with the results.

**Comment by kaustavghosh06** [comment]
@kimfucious Thanks for getting back to us on this. Closing this issue for now but please comment on this thread if you see this again.

**Comment by kimfucious** [comment]
Hi @kaustavghosh06,

This did reoccur.  It didn't prior, I believe, as I was updating a different function than the one that apparently causes this error.

Here's the error that occurs when I run `amplify push` on the function in question:
```console
PS D:\Users\Kim\Dev\Sites\workspace\slugbucket> amplify push
√ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name                | Operation | Provider plugin   |
| -------- | ---------------------------- | --------- | ----------------- |
| Function | myCoolFunction               | Update    | awscloudformation |
...

? Are you sure you want to continue? Yes
× An error occurred when pushing the resources to the cloud

Connection timed out after 120000ms
An error occurred during the push operation: Connection timed out after 120000ms
```
This function is a bit larger that other functions that I've pushed before, which may be part of the problem:
* The size of the dist directory for this function is: 22MB
* The size of the src directory is: 127MB

**Comment by kimfucious** [comment]
Hi @kaustavghosh06,

I'm sure you're busy, but I'm not sure you see comment activity once an issue is closed.  

I've wait a bit and open a new ticket, if I don't hear back.

**Comment by gabrielgrover** [comment]
I get this same issue as well.  I have to use amplify push several times before cli gets passed "uploading files..." state.

**Comment by jaibatrik** [comment]
Disabling firewall did not help me.

**Comment by gabrielgrover** [comment]
So this problem is still persisting for me.  The issue for me is that my project has a lot of lambda functions.  When I use amplify push on a newly created environment i get timeouts because my upload speed is not the greatest. Maybe increase the timeout threshold?

**Comment by wellmmer** [comment]
Hi @kaustavghosh06 and @kimfucious 

I'm facing the same issue right now... I did a bash script to build my Node.js lambda, once they were coded using Typescript I needed to do it. But when I run **"amplify push -y"** I'm always getting the error below:

```
Connection timed out after 120000ms
An error occurred during the push operation: Connection timed out after 120000ms
```

![image](https://user-images.githubusercontent.com/37679777/113061012-c5cb9c80-9187-11eb-92f0-15610e939662.png)


But the weird thing is that if I just update one resource like my API Gateway, so then I don't get any error, and it works fine!


Amplify CLI Version
![Screen Shot 2021-03-30 at 18 44 51](https://user-images.githubusercontent.com/37679777/113061144-05928400-9188-11eb-8446-6cd72be9da04.png)


Any help guys ?

**Comment by wellmmer** [comment]
> Hi @kaustavghosh06 and @kimfucious
> 
> I'm facing the same issue right now... I did a bash script to build my Node.js lambda, once they were coded using Typescript I needed to do it. But when I run **"amplify push -y"** I'm always getting the error below:
> 
> ```
> Connection timed out after 120000ms
> An error occurred during the push operation: Connection timed out after 120000ms
> ```
> 
> ![image](https://user-images.githubusercontent.com/37679777/113061012-c5cb9c80-9187-11eb-92f0-15610e939662.png)
> 
> But the weird thing is that if I just update one resource like my API Gateway, so then I don't get any error, and it works fine!
> 
> Amplify CLI Version
> ![Screen Shot 2021-03-30 at 18 44 51](https://user-images.githubusercontent.com/37679777/113061144-05928400-9188-11eb-8446-6cd72be9da04.png)
> 
> Any help guys ?

Sometimes the error is this one...

![image](https://user-images.githubusercontent.com/37679777/113061841-11327a80-9189-11eb-8a23-2b039d7836d5.png)

**Comment by wellmmer** [comment]
Sometimes the error is this one below...

![image](https://user-images.githubusercontent.com/37679777/113061912-37581a80-9189-11eb-8645-48c3d4189bab.png)

**Comment by jazu-dev** [comment]
Hello @kaustavghosh06 this is also happening to me consistently. I'm using:

- Node version: v14.15.4
- Amplify CLI version: @aws-amplify/cli@4.50.2 (latest, AFAIK)

```
$ amplify push
✔ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name         | Operation | Provider plugin   |
| -------- | --------------------- | --------- | ----------------- |
| Storage  | dynamo47866d4f        | Create    | awscloudformation |
| Function | reactamplify2829389a6 | Create    | awscloudformation |
| Auth     | cognito4693ee74       | Create    | awscloudformation |
| Api      | apie323780f           | Create    | awscloudformation |
? Are you sure you want to continue? Yes
✖ An error occurred when pushing the resources to the cloud

Connection timed out after 120000ms
An error occurred during the push operation: Connection timed out after 120000ms
```

I have checked my internet connection and tried this multiple times but it's always the same. Shall we reopen the issue?
