### ISSUE TITLE
Create Function - package.json name does not match regexp warning

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-cli#7905]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

latest

### Amplify CLI Version

latest

### What operating system are you using?

macOS

### Amplify Categories

function

### Amplify Commands

add

### Describe the bug

When you create an amplify function with capitals, there is a warning that appears for the name field in package.json that is created...

String does not match the pattern of "^(?:@[a-z0-9-*~][a-z0-9-*._~]*/)?[a-z0-9-~][a-z0-9-._~]*$".

### Expected behavior

No warning should appear...name field should be modified to lowercase...

### Reproduction steps

Create a function called testFunction

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @GeorgeBellTMH :wave: thanks for raising this! I also see this warning from npm regarding an invalid name field value. Thankfully this does not impact our deployments or usage, however it does not follow the [spec for package.json name field](https://docs.npmjs.com/creating-a-package-json-file#required-name-and-version-fields). Marking this as a feature request to force the package name to all lowercase when adding a function with capital letters in the name.

**Comment by studpeps** [comment]
Hey @GeorgeBellTMH and @josefaidt, I am trying to reproduce the issue but have been unable to, has this been arising when deploying or when creating the function locally
I did the following steps to produce the bug:

$ amplify add function
? Select which capability you want to add: Lambda function (serverless function)
? Provide an AWS Lambda function name: testFunction
? Choose the runtime that you want to use: NodeJS
? Choose the function template that you want to use: Hello World

Available advanced settings:
- Resource access permissions        
- Scheduled recurring invocation     
- Lambda layers configuration        
- Environment variables configuration
- Secret values configuration

? Do you want to configure advanced settings? No
? Do you want to edit the local lambda function now? No
Successfully added resource testFunction locally.  

It gives me a success message for lambda function

**Comment by josefaidt** [comment]
Hey @studpeps :wave: this is an npm warning and does not impact creation or pushes of the Lambda function. It can be found in the function's `package.json` file:

![image](https://user-images.githubusercontent.com/5033303/128909595-dbdd1e94-7c70-474a-8691-8b8a9dc3aa3a.png)

[Reference for package.json "name" specification](https://docs.npmjs.com/creating-a-package-json-file#required-name-and-version-fields)

**Comment by studpeps** [comment]
Oh yes right, thank you @josefaidt

**Comment by GeorgeBellTMH** [comment]
At the least can we implement this on new functions? I would also suggest asking if it should be fixed on updates...there doesn't seem to be a lot of good reasons to have an incorrect package.json...

**Comment by fossamagna** [comment]
> I've opened #8051 as a revert. I do think we should address this issue, but I think we can do it in a less breaking way.

Hey @cjihrig. I considered it as follows.
* We can contain upper case characters in function name as before
* Only `name` in `package.json` will be changed to lower case.

What do you think on this?

**Comment by cjihrig** [comment]
@fossamagna that could potentially work.

**Comment by yogesh432kumar** [comment]
I'm still getting this error - seems like my Amplify packages might be old...any suggestion on what I could update to resolve this issue.
