### ISSUE TITLE
Directives not recognised when compiling

### ISSUE THREAD

**Issue by Lazarus404** [aws-amplify/amplify-cli#9082]
**Which Category is your question related to?**

GraphQL / DataStore

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system

7.5.2

**What AWS Services are you utilizing?**

Creating GraphQL relationships

**Provide additional details e.g. code snippets**

Running `amplify api gql-compile` responds with:

```
🛑 Unknown directive "connection".
Unknown directive "connection".
Unknown directive "connection".
Unknown directive "connection".
Unknown directive "connection".
Unknown directive "key".
Unknown directive "key".
Unknown directive "key".
Unknown directive "key".
Unknown directive "connection".
Unknown directive "connection".
Error: Unknown directive "connection".
Unknown directive "connection"
Unknown directive "connection".
Unknown directive "connection".
Unknown directive "connection".
Unknown directive "key".
Unknown directive "key".
Unknown directive "key".
Unknown directive "key".
Unknown directive "connection".
Unknown directive "connection".
    at assertValidSDL (/snapshot/node_modules/graphql/validation/validate.js:108:11)
    at buildASTSchema (/snapshot/node_modules/graphql/utilities/buildASTSchema.js:71:34)
    at validateModelSchema (/snapshot/node_modules/@aws-amplify/graphql-transformer-core/lib/transformation/validation.js:100:56)
    at GraphQLTransform.transform (/snapshot/node_modules/@aws-amplify/graphql-transformer-core/lib/transformation/transform.js:161:61)
    at _buildProject (/snapshot/node_modules/amplify-provider-awscloudformation/lib/graphql-transformer/transform-graphql-schema.js:510:37)
    at buildAPIProject (/snapshot/node_modules/amplify-provider-awscloudformation/lib/graphql-transformer/transform-graphql-schema.js:474:24)
    at transformGraphQLSchema (/snapshot/node_modules/amplify-provider-awscloudformation/lib/graphql-transformer/transform-graphql-schema.js:360:29)
    at Object.executeAmplifyCommand (/snapshot/node_modules/@aws-amplify/amplify-category-api/lib/index.js:200:9)
    at executePluginModuleCommand (/snapshot/node_modules/@aws-amplify/cli/lib/execution-manager.js:187:5)
    at executeCommand (/snapshot/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at Object.run (/snapshot/node_modules/@aws-amplify/cli/lib/index.js:162:9)
```

**Comment by cjihrig** [comment]
`@key` and `@connection` are directives in v1 of the GraphQL Transformer. We released [GraphQL Transformer v2](https://aws.amazon.com/blogs/mobile/aws-amplify-announces-the-new-graphql-transformer-v2-more-feature-rich-flexible-and-extensible/) this week in v7.5.0. It is now on by default for newly created APIs. Existing APIs should continue to use v1 unless you migrate to v2.

Was this a newly created API?

**Comment by Lazarus404** [comment]
It was created yesterday.  I'm going to try updating everything and will see if that fixes it.  Thanks for the response.  I'll let you know if updating fixes it.

**Comment by Lazarus404** [comment]
So, I updated to latest
```
  "dependencies": {
    "@aws-amplify/ui-components": "^1.9.5",
    "aws-amplify": "^4.3.8",
    ...
  },
```
and I still get the same result

**Comment by cjihrig** [comment]
You need to either update your GraphQL schema to use the new directives, or downgrade to v1 of the transformer. You can downgrade by setting the `transformerversion` feature flag to 1 and the `useexperimentalpipelinedtransformer` feature flag to false. These feature flags can be found in your project's `cli.json` file. However, if this is a new API, I'd recommend migrating to a v2 schema.

**Comment by Lazarus404** [comment]
Thank you.  I just recreated everything from scratch, but still seeing the issue.  Here is my schema
```
type User @model @auth(rules: [{allow: groups, groups: ["owners"], operations: [read, create, update, delete]}, {allow: public}]) {
  id: ID!
  siteID: ID
  directories: [UserDirectory] @connection(keyName: "byUser", fields: ["id"])
  email: String!
  active: Boolean
}

type File @model @auth(rules: [{allow: groups, groups: ["owners"], operations: [read, create, update, delete]}, {allow: public}]) {
  id: ID!
  s3ID: String!
  directoryID: ID
  name: String!
  type: String
  size: Int
  path: String
  active: Boolean
}

type Directory @model @auth(rules: [{allow: groups, groups: ["owners"], operations: [read, create, update, delete]}, {allow: public}]) {
  id: ID!
  siteID: ID
  name: String!
  path: String
  files: [File] @connection(keyName: "byDirectory", fields: ["id"])
  parentID: ID
  users: [UserDirectory] @connection(keyName: "byDirectory", fields: ["id"])
  active: Boolean
}

type Site @model @auth(rules: [{allow: groups, groups: ["owners"], operations: [read, create, update, delete]}, {allow: public}]) {
  id: ID!
  name: String!
  subdomain: String!
  directories: [Directory] @connection(keyName: "bySite", fields: ["id"])
  ownerEmail: String!
  users: [User] @connection(keyName: "bySite", fields: ["id"])
  active: Boolean
}

type UserDirectory @model(queries: null) @key(name: "byDirectory", fields: ["directoryID", "userID"]) @auth(rules: [{allow: groups, groups: ["owners"], operations: [read, create, update, delete]}, {allow: public}, {allow: groups, groups: ["owners"], operations: [read, create, update, delete]}, {allow: public}]) {
  id: ID!
  siteID: ID!
  userID: ID!
  directoryID: ID!
  user: User! @connection(fields: ["userID"])
  directory: Directory! @connection(fields: ["directoryID"])
}
```

**Comment by Straubulous** [comment]
@Lazarus404 - Looking at the schema, it is definitely V1 schema (v2 schema doesn't use @connection) , which is what you'd expect to see if generating with a CLI version less than 7.5.0 (assuming no feature flags configured). Very interested to see what you get when upgraded to 7.5x.

**Comment by Straubulous** [comment]
@Lazarus404  an interesting question is "why is CLI using GQL v2 when the schema is V1".  This is an issue that we're investigating and we think it may have to do with the absence of a feature flag when upgrading to CLI 7.5x with a schema from an older build of CLI.   Can you confirm if you have these two feature flags and what they're set to? transformerversion and useexperimentalpipelinedtransformer

**Comment by Lazarus404** [comment]
Hi @Straubulous.  I'm afraid I completely killed and removed the older app.  I'd copied the schema and my functions in the resolver folder to the new app.  The previous app did go into a state where the GQL couldn't compile after updating, so it may be as you say, but I'm unable to check that now.

**Comment by Lazarus404** [comment]
@cjihrig I've got the GQL compiling and I can push, but the data page is blank in the Admin UI.  Is that yet to be updated to match these transformer updates?

**Comment by Lazarus404** [comment]
So, my GQL now looks like this
```
type User @model
  @auth(rules: [
    {allow: private, operations: [read, create, update, delete]}, {allow: public}
  ]) {
  userID: ID! @primaryKey
  siteID: ID! @index(name: "bySiteID")
  directories: [UserDirectory] @hasMany
  email: String! @index(name: "byEmail")
  active: Boolean
}

type File @model
  @auth(rules: [
    {allow: private, operations: [read, create, update, delete]},
    {allow: public}
  ]) {
  siteID: ID! @primaryKey
  s3ID: String!
  directoryID: ID
  name: String!
  type: String
  size: Int
  path: String
  active: Boolean
}

type Directory @model
  @auth(rules: [
    {allow: private, operations: [read, create, update, delete]},
    {allow: public}
  ]) {
  directoryID: ID! @primaryKey
  siteID: ID
  name: String!
  path: String
  files: [File] @hasMany
  parentID: ID
  users: [UserDirectory] @hasMany
  active: Boolean
}

type Site @model
  @auth(rules: [
    {allow: private, operations: [read, create, update, delete]},
    {allow: public}
  ]) {
  siteID: ID! @primaryKey
  name: String!
  subdomain: String!
  directories: [Directory] @hasMany
  ownerEmail: String!
  users: [User] @hasMany
  active: Boolean
}

type UserDirectory @model(queries: null)
  @auth(rules: [
    {allow: private, operations: [read, create, update, delete]},
    {allow: public}
  ]) {
  userDirectoryID: ID! @primaryKey
  siteID: ID! @index(name: "bySite") @index(name: "bySiteByUser", sortKeyFields: ["userID"])
  userID: ID!
  directoryID: ID!
  user: User! @hasOne
  directory: Directory! @hasOne
}
```
but I'm getting this error
```
@auth directive with 'apiKey' provider found, but the project has no API Key authentication provider configured
```
I only want to use cognito.  Do I have options, here?

**Comment by Lazarus404** [comment]
Okay, this is all fixed.  Thanks very much for your help, guys.
